package kg.peaksoft.bilingualb4.models.enums;

public enum QuestionType {
    SELECT_REAL_ENGLISH_WORD,
    LISTEN_AND_SELECT_WORD,
    TYPE_WHAT_YOU_HEAR,
    RECORD_SAYING,
    DESCRIBE_IMAGE,
    RESPOND_IN_AT_LEAST_N_WORDS,
    HIGHLIGHTS_THE_ANSWER,
    SELECT_MAIN_IDEA,
    SUBMITTED_RESULTS_PAGE
}
