spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 25
    username: mailfromspringboot0@gmail.com
    password: okm9ijnuhb
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
    port: 5000
    error:
        include-message: always
application:
  jwt:
    secret-key: HRlELXqpSB
    token-prefix: Bearer
    expiration-date-after-days: 30
cloud:
  aws:
    credentials:
      access-key: AKIAXOPE6YK5LIED47Q3
      secret-key: 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

    region:
      static: eu-central-1
    stack:
      auto: false
