application:
    jwt:
        expiration-date-after-days: 30
        secret-key: HRlELXqpSB
        token-prefix: Bearer
server:
    error:
        include-message: always
    port: 4040
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 12345
        url: jdbc:postgresql://localhost:5432/bilingual
        username: postgres
    flyway:
        baseline-on-migrate: true
        locations: classpath:db/migration
        schemas: public
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: false
